# Generated by Django 4.1.1 on 2022-09-26 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='', verbose_name='题目')),
                ('answer_A', models.CharField(default='', max_length=200, verbose_name='A选项')),
                ('answer_B', models.CharField(default='', max_length=200, verbose_name='B选项')),
                ('answer_C', models.CharField(default='', max_length=200, verbose_name='C选项')),
                ('answer_D', models.CharField(default='', max_length=200, verbose_name='D选项')),
                ('right_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1, verbose_name='正确选项')),
                ('analysis', models.TextField(default='暂无', verbose_name='题目解析')),
                ('score', models.PositiveSmallIntegerField(default=5, verbose_name='分值')),
                ('level', models.CharField(choices=[('1', '入门'), ('2', '简单'), ('3', '普通'), ('4', '较难'), ('5', '困难')], default='1', max_length=1, verbose_name='难度等级')),
            ],
            options={
                'verbose_name': '选择题',
                'verbose_name_plural': '选择题',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20, verbose_name='年级')),
                ('major', models.CharField(max_length=20, verbose_name='专业')),
                ('clazz', models.CharField(max_length=20, verbose_name='班级')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='考试名称')),
                ('exam_date', models.DateField(default='', verbose_name='考试日期')),
                ('total_time', models.PositiveSmallIntegerField(default=120, help_text='时长按照分钟填写', verbose_name='时长')),
                ('major', models.CharField(default='', max_length=20, verbose_name='专业')),
                ('clazzs', models.ManyToManyField(to='exam.class', verbose_name='参加考试的班级')),
            ],
            options={
                'verbose_name': '考试',
                'verbose_name_plural': '考试',
                'db_table': 'exam_info',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Fill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='', verbose_name='题目')),
                ('right_answer', models.CharField(default='', max_length=200, verbose_name='正确答案')),
                ('analysis', models.TextField(default='暂无', verbose_name='题目解析')),
                ('score', models.PositiveSmallIntegerField(default=5, verbose_name='分值')),
                ('level', models.CharField(choices=[('1', '入门'), ('2', '简单'), ('3', '普通'), ('4', '较难'), ('5', '困难')], default='1', max_length=1, verbose_name='难度等级')),
            ],
            options={
                'verbose_name': '填空题',
                'verbose_name_plural': '填空题',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='', verbose_name='题目')),
                ('right_answer', models.CharField(choices=[('T', '正确'), ('F', '错误')], default='T', max_length=1, verbose_name='正确答案')),
                ('analysis', models.TextField(default='暂无', verbose_name='题目解析')),
                ('score', models.PositiveSmallIntegerField(default=5, verbose_name='分值')),
                ('level', models.CharField(choices=[('1', '入门'), ('2', '简单'), ('3', '普通'), ('4', '较难'), ('5', '困难')], default='1', max_length=1, verbose_name='难度等级')),
            ],
            options={
                'verbose_name': '判断题',
                'verbose_name_plural': '判断题',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='试卷名称')),
                ('score', models.PositiveSmallIntegerField(default=100, verbose_name='总分')),
                ('choice_number', models.PositiveSmallIntegerField(default=5, verbose_name='选择题数')),
                ('fill_number', models.PositiveSmallIntegerField(default=5, verbose_name='填空题数')),
                ('judge_number', models.PositiveSmallIntegerField(default=10, verbose_name='判断题数')),
                ('level', models.CharField(choices=[('1', '入门'), ('2', '简单'), ('3', '普通'), ('4', '较难'), ('5', '困难')], default='1', max_length=1, verbose_name='难度等级')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sno', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='学号')),
                ('name', models.CharField(default='', max_length=20, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('m', '男'), ('f', '女')], default='', max_length=1, verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('pwd', models.CharField(max_length=20, verbose_name='密码')),
                ('clazz', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='exam.class', verbose_name='班级')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'db_table': 'student',
                'ordering': ['sno'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default='', verbose_name='分数')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam', verbose_name='考试')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '学生成绩',
                'verbose_name_plural': '学生成绩',
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='paper',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='exam.paper', verbose_name='试卷'),
        ),
    ]
