# Generated by Django 4.1.1 on 2022-09-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_teacher_alter_choice_id_alter_class_id_alter_exam_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=18, verbose_name='年龄'),
        ),
    ]
