# Generated by Django 4.1.1 on 2022-09-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_alter_student_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pwd',
            field=models.CharField(max_length=256, verbose_name='密码'),
        ),
    ]
