# Generated by Django 4.1.1 on 2022-09-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_student_age_alter_student_pwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='', max_length=20, verbose_name='邮箱'),
        ),
    ]
