# Generated by Django 4.1.1 on 2022-09-28 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='tno',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='exam.teacher', verbose_name='老师'),
        ),
    ]
