# Generated by Django 4.1.1 on 2022-09-28 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_class_tno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='tno',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.teacher', verbose_name='老师'),
        ),
    ]
