# Generated by Django 4.1.1 on 2022-10-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_paper_choice_question_paper_fill_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='题号'),
        ),
        migrations.AlterField(
            model_name='fill',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='题号'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='题号'),
        ),
    ]
